### PR TITLE
Added escaping for backslashes on path to prevent handlebar escaping

### PR DESCRIPTION
**Pull request by wtvamp**

### CODE REVIEW

**Comment by thlorenz** [comment]
Could you please add a test that fails before your change but passes now?

**Comment by wtvamp** [comment]
I could try - what testing framework does it use?

On Thu, Aug 6, 2015 at 1:28 PM, Thorsten Lorenz notifications@github.com
wrote:

> Could you please add a test that fails before your change but passes now?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/thlorenz/bromote/pull/10#issuecomment-128498329.

## 

Warren Thompson
Founder
Thompson Web, Inc.
(503)383-9489
http://www.thompsonwebinc.com

**Comment by thlorenz** [comment]
> I could try - what testing framework does it use?

Should be clear by looking at the existing tests ;)

**Comment by thlorenz** [comment]
Most likely you'd add your tests somewhere here: https://github.com/thlorenz/bromote/tree/master/test/escaped-characters

**Comment by thlorenz** [comment]
Or better create another folder put your tests there and add them here: https://github.com/thlorenz/bromote/blob/master/test/run-all.js

**Comment by the-simian** [comment]
Hey i can confirm this fix works - any chance of pulling this within the year?

**Comment by thlorenz** [comment]
> Could you please add a test that fails before your change but passes now?

Asked for that over two years ago ;).
Until then I won't merge, sorry

**Pull request closed without merging**
