### PR TITLE
JSONP Injection working.

### PR DESCRIPTION
**Pull request by toddself**
Uses JSONPject to handle the loading of scripts with a callback parameter into the document.

Passes a noop callback into the loader, and instead wraps the original callback in a newly defined function which is the parameter passed into the JSONP callback.

### CODE REVIEW

**Comment by thlorenz** [comment]
Nice!
Could you please change the underscore name to JavaScript naming convention (camelCase) and then squash all commits into one?

Will merge and publish it then.
Thanks.

**Comment by toddself** [comment]
Changed and squashed.

**Comment by thlorenz** [comment]
Had to make a couple of changes, but published as 0.2 now :)

**Comment by thlorenz** [comment]
btw not sure what [this](https://github.com/thlorenz/bromote/blob/master/test/jsonp-callbacks/build.js#L10) refers to and/or if it still needs to be there.

**Comment by toddself** [comment]
Awesome thanks!  That comment no longer applies -- in order to access Google Maps you need an API key, which limits the number of map calls your account can make.  I made an API key just for testing which is only accessible from 127.0.0.1 and localhost to prevent people from using it for their own live sites.

**Pull request merged**
